### ISSUE TITLE
Version 1.6.0

### ISSUE THREAD

**Issue by sigrunixia** [Obsidian-TTRPG-Community/Fantasy-Statblocks-CSS-Development#3]
Welcome @Wren1234

Since we're all so busy, I wanted to do incremental updates so we keep doing some work on this.

For 1.5.x, I am thinking we make the change to [class*=Pathfinder2e]. This would shorten the CSS needed even further, and make it so we don't need to have a names file. 

Anything else we want to tackle?

**To-do**
- [ ] Class ID Changes
- [x] Remove Popover from the Equation (Its not a breaking change, but it breaks a lot!)
- [ ] ITS-Proof The Theme

**Comment by sigrunixia** [comment]
Maybe we need to tackle the trait_01 and rare_01 stuff since thats also a major css change..  That would make this a 1.6.0 bump.

**Comment by mProjectsCode** [comment]
I am on vacation this week. But I can help with these changes next week, when I am back home.

**Comment by sigrunixia** [comment]
No worries. I am going to push my CSS update to Statblocks as well, so we'll need some changes done. This will end up being a 1.6.0 because of those changes.
